name: Deploy to Render

on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create server .env file
        env:
          SERVER_ENV_FILE: ${{ secrets.SERVER_ENV }}
        run: |
          printf "%s" "${SERVER_ENV_FILE}" > server/.env

      - name: Create shared .env file
        env:
          SHARED_ENV_FILE: ${{ secrets.SHARED_ENV }}
        run: |
          printf "%s" "${SHARED_ENV_FILE}" > shared/.env

      - name: Print SERVER_ENV for debugging
        run: |
          echo "SERVER_ENV: ${{ secrets.SERVER_ENV }}"

      - name: Print SHARED_ENV for debugging
        run: |
          echo "SHARED_ENV: ${{ secrets.SHARED_ENV }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.14.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --no-cache --push --tag ${{ secrets.DOCKER_HUB_USERNAME }}/ansambl:latest .

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          data=$(jq -n --arg clearCache "clear" '{clearCache: $clearCache}')
          curl -X POST "https://api.render.com/v1/services/srv-cp5941q1hbls73fbvgcg/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data "$data"
